# Generated by Django 4.0.4 on 2022-05-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_medicos_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='especialidad_turno',
        ),
    ]
